# Generated by Django 3.0.8 on 2020-08-11 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productSize', '0003_auto_20200811_0350'),
        ('provider', '0002_provider_code'),
        ('productColor', '0003_productcolor_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productColor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productColor.ProductColor')),
                ('productSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productSize.ProductSize')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider')),
            ],
        ),
    ]
