# Generated by Django 3.0.8 on 2020-08-11 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packingType', '0001_initial'),
        ('stock', '0002_stock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='packingType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='packingType.PackingType'),
            preserve_default=False,
        ),
    ]
