# Generated by Django 3.0.8 on 2020-08-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stock_packingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='providerMakat',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
