# Generated by Django 3.0.8 on 2020-08-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_stock_providermakat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='amount'),
        ),
    ]
