# Generated by Django 3.0.8 on 2020-08-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='catalogNumber',
            field=models.CharField(default='zzz', max_length=120, verbose_name='catalog number'),
            preserve_default=False,
        ),
    ]
