# Generated by Django 3.0.8 on 2020-08-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stock_catalognumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='catalogNumber',
        ),
    ]
