# Generated by Django 3.0.8 on 2020-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_remove_stock_catalognumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'מלאי', 'verbose_name_plural': 'מלאים'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='כמות'),
        ),
    ]
