# Generated by Django 3.0.8 on 2020-09-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productColor', '0007_auto_20200908_1726'),
        ('productSize', '0005_auto_20200906_1538'),
        ('product', '0021_auto_20200908_1726'),
        ('packingType', '0002_auto_20200906_1538'),
        ('provider', '0005_auto_20200906_1538'),
        ('stock', '0008_auto_20200906_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='packingType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packingType.PackingType', verbose_name='שיטת אריזה'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='שם המוצר'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productColor.ProductColor', verbose_name='צבע'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productSize.ProductSize', verbose_name='גודל'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider', verbose_name='ספק המוצר'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='providerMakat',
            field=models.CharField(blank=True, max_length=50, verbose_name='מק"ט ספק'),
        ),
    ]
