# Generated by Django 3.0.8 on 2020-09-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packingType', '0003_auto_20200913_1831'),
        ('productColor', '0008_auto_20200913_1831'),
        ('product', '0022_auto_20200913_1831'),
        ('productSize', '0006_auto_20200913_1831'),
        ('provider', '0006_auto_20200913_1831'),
        ('stock', '0009_auto_20200908_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stock', 'verbose_name_plural': 'Stocks'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='stock at us'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='packingType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packingType.PackingType', verbose_name='packing type'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productColor.ProductColor', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productSize.ProductSize', verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider', verbose_name='product provider'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='providerMakat',
            field=models.CharField(blank=True, max_length=50, verbose_name='provider makat'),
        ),
    ]
