# Generated by Django 3.0.8 on 2020-09-13 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_auto_20200913_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='provider_has_stock',
            field=models.BooleanField(default=True, verbose_name='exist at provider'),
        ),
        migrations.AddField(
            model_name='stock',
            name='provider_resupply_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='provider resupply date'),
            preserve_default=False,
        ),
    ]
