# Generated by Django 3.0.8 on 2020-09-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200915_1933'),
        ('packingType', '0004_auto_20200915_1933'),
        ('productColor', '0009_auto_20200915_1933'),
        ('productSize', '0007_auto_20200915_1933'),
        ('provider', '0007_auto_20200915_1933'),
        ('stock', '0013_auto_20200913_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'מלאי', 'verbose_name_plural': 'מלאים'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='כמות אצלנו'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='packingType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packingType.PackingType', verbose_name='שיטת אריזה'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='שם מוצר'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productColor.ProductColor', verbose_name='צבע'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productSize.ProductSize', verbose_name='גודל'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider', verbose_name='ספק מוצר'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='providerMakat',
            field=models.CharField(blank=True, max_length=50, verbose_name='מק"ט של הספק'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='provider_has_stock',
            field=models.BooleanField(default=True, verbose_name='קיים אצל הספק'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='provider_resupply_date',
            field=models.DateTimeField(null=True, verbose_name='תאריך חידוש מלאי אצל הספק'),
        ),
    ]
