# Generated by Django 3.0.8 on 2020-09-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0008_auto_20200924_2216'),
        ('packingType', '0004_auto_20200915_1933'),
        ('provider', '0008_auto_20200924_2216'),
        ('product', '0024_auto_20200924_2216'),
        ('productColor', '0010_auto_20200924_2216'),
        ('stock', '0014_auto_20200915_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'default_related_name': 'stocks', 'verbose_name': 'מלאי', 'verbose_name_plural': 'מלאים'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='כמות אצלנו'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='packingType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='packingType.PackingType', verbose_name='שיטת אריזה'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.Product', verbose_name='שם מוצר'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productColor.ProductColor', verbose_name='צבע'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='productSize.ProductSize', verbose_name='גודל'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='provider.Provider', verbose_name='ספק מוצר'),
        ),
    ]
