# Generated by Django 3.0.8 on 2020-08-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_remove_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title'], 'verbose_name_plural': 'Categories'},
        ),
    ]
