# Generated by Django 3.0.8 on 2020-08-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20200809_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='itemsCount',
            field=models.IntegerField(default=0),
        ),
    ]
