# Generated by Django 3.0.8 on 2020-08-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_itemscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catalog_rep',
            field=models.CharField(default='A', max_length=1, verbose_name='catalog representation'),
            preserve_default=False,
        ),
    ]
