# Generated by Django 3.0.8 on 2020-08-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_catalog_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catalog_rep',
            field=models.CharField(blank=True, max_length=1, verbose_name='catalog representation'),
        ),
    ]
