# Generated by Django 3.0.8 on 2020-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20200815_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title'], 'verbose_name': 'קטגוריה', 'verbose_name_plural': 'קטגויות'},
        ),
        migrations.AlterField(
            model_name='category',
            name='catalog_rep',
            field=models.CharField(blank=True, max_length=1, verbose_name='מספר קטלוג'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=250, verbose_name='כותרת'),
        ),
    ]
