# Generated by Django 3.0.8 on 2020-09-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_remove_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title'], 'verbose_name': 'קטגוריה', 'verbose_name_plural': 'קטגוריות'},
        ),
        migrations.AlterField(
            model_name='category',
            name='catalog_rep',
            field=models.CharField(blank=True, max_length=1, verbose_name='ייצוג קטלוג'),
        ),
    ]
