# Generated by Django 3.0.8 on 2020-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20200913_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-title'], 'verbose_name': 'קטגוריה', 'verbose_name_plural': 'קטגוריות'},
        ),
        migrations.AlterField(
            model_name='category',
            name='catalog_rep',
            field=models.CharField(blank=True, max_length=1, verbose_name='ייצוג קטלוגי'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=250, verbose_name='כותרת'),
        ),
    ]
