# Generated by Django 3.0.8 on 2020-08-02 15:08

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='color name')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='color')),
            ],
        ),
    ]
