# Generated by Django 3.0.8 on 2020-08-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_remove_color_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default=0, max_length=30, verbose_name='color name'),
            preserve_default=False,
        ),
    ]
