# Generated by Django 3.0.8 on 2020-09-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0005_auto_20200906_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'צבע', 'verbose_name_plural': 'צבעים'},
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='שם הצבע'),
        ),
    ]
