# Generated by Django 3.0.8 on 2020-09-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0006_auto_20200908_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='שם צבע'),
        ),
    ]
