# Generated by Django 3.0.8 on 2020-09-15 16:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0008_auto_20200913_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'צבע', 'verbose_name_plural': 'צבעים'},
        ),
        migrations.AlterField(
            model_name='color',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='צבע'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='שם צבע'),
        ),
    ]
