# Generated by Django 3.0.8 on 2020-10-12 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogImages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='כותרת')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='ThroughImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(unique=True, verbose_name='משקל')),
                ('catalogAlbum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogAlbum.CatalogAlbum')),
                ('catalogImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogImages.CatalogImage')),
            ],
            options={
                'ordering': ['weight'],
            },
        ),
        migrations.AddField(
            model_name='catalogalbum',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', through='catalogAlbum.ThroughImage', to='catalogImages.CatalogImage'),
        ),
    ]
