# Generated by Django 3.0.8 on 2020-10-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='relatedAlbums',
            field=models.ManyToManyField(to='catalogAlbum.CatalogAlbum'),
        ),
    ]
