# Generated by Django 3.0.8 on 2020-10-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogImages', '0001_initial'),
        ('catalogAlbum', '0003_auto_20201013_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogalbum',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', through='catalogAlbum.ThroughImage', to='catalogImages.CatalogImage'),
        ),
    ]
