# Generated by Django 3.0.8 on 2020-10-13 06:56

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0005_remove_catalogalbum_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogAlbum.CatalogAlbum'),
        ),
    ]
