# Generated by Django 3.0.8 on 2020-10-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0006_catalogalbum_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogalbum',
            name='level',
        ),
        migrations.RemoveField(
            model_name='catalogalbum',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='catalogalbum',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='catalogalbum',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='catalogalbum',
            name='tree_id',
        ),
    ]
