# Generated by Django 3.0.8 on 2020-10-14 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0007_auto_20201013_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalogAlbum.CatalogAlbum'),
        ),
        migrations.AlterField(
            model_name='catalogalbum',
            name='slug',
            field=models.SlugField(max_length=120, verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='catalogalbum',
            unique_together={('slug', 'parent')},
        ),
    ]
