# Generated by Django 3.0.8 on 2020-10-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogAlbum', '0009_auto_20201014_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogalbum',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogalbum',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogalbum',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogalbum',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='catalogalbum',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='catalogalbum',
            name='parent',
        ),
    ]
