# Generated by Django 3.0.8 on 2020-09-08 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0021_auto_20200908_1726'),
        ('productSize', '0005_auto_20200906_1538'),
        ('order', '0001_initial'),
        ('productColor', '0007_auto_20200908_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='כמות')),
                ('add_printing', models.BooleanField(verbose_name='add printing')),
                ('add_embroidery', models.BooleanField(verbose_name='add embroidery')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productColor.ProductColor', verbose_name='צבע')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productSize.ProductSize', verbose_name='גודל')),
            ],
            options={
                'verbose_name': 'Order detail',
                'verbose_name_plural': 'Order details',
            },
        ),
    ]
