# Generated by Django 3.0.8 on 2020-09-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200915_1933'),
        ('productColor', '0009_auto_20200915_1933'),
        ('product', '0023_auto_20200915_1933'),
        ('productSize', '0007_auto_20200915_1933'),
        ('order_detail', '0002_auto_20200913_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': 'פרטי הזמנה', 'verbose_name_plural': 'פרטי הזמנות'},
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='add_embroidery',
            field=models.BooleanField(verbose_name='הוסף רקמה'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='add_printing',
            field=models.BooleanField(verbose_name='הוסף הדפסה'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='amount',
            field=models.IntegerField(verbose_name='כמות'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productColor.ProductColor', verbose_name='צבע'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order', verbose_name='הזמנה'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='מוצר'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productSize.ProductSize', verbose_name='גודל'),
        ),
    ]
