# Generated by Django 3.0.8 on 2020-08-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='code',
            field=models.CharField(default='A', max_length=1, verbose_name='code'),
            preserve_default=False,
        ),
    ]
