# Generated by Django 3.0.8 on 2020-08-11 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_provider_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='color',
        ),
    ]
