# Generated by Django 3.0.8 on 2020-08-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_remove_provider_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='code',
            field=models.CharField(default='A', max_length=1, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='providerId',
            field=models.CharField(blank=True, max_length=150, verbose_name='private compeny'),
        ),
    ]
