# Generated by Django 3.0.8 on 2020-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0004_auto_20200816_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'ספק', 'verbose_name_plural': 'ספקים'},
        ),
        migrations.AlterField(
            model_name='provider',
            name='code',
            field=models.CharField(default='A', max_length=1, verbose_name='קוד'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=150, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='providerId',
            field=models.CharField(blank=True, max_length=150, verbose_name='חברה פרטית'),
        ),
    ]
