# Generated by Django 3.0.8 on 2020-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_auto_20200906_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
        migrations.AlterField(
            model_name='provider',
            name='code',
            field=models.CharField(default='A', max_length=1, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='providerId',
            field=models.CharField(blank=True, max_length=150, verbose_name='private compeny'),
        ),
    ]
