# Generated by Django 3.0.8 on 2020-09-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_auto_20200915_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'default_related_name': 'providers', 'verbose_name': 'ספק', 'verbose_name_plural': 'ספקים'},
        ),
    ]
