# Generated by Django 3.0.8 on 2020-08-02 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sizes', serialize=False, to='product.Product')),
                ('size32', models.BooleanField(default=True, verbose_name='32')),
                ('size33', models.BooleanField(default=True, verbose_name='33')),
                ('size34', models.BooleanField(default=True, verbose_name='34')),
                ('size35', models.BooleanField(default=True, verbose_name='35')),
                ('size36', models.BooleanField(default=True, verbose_name='36')),
                ('size37', models.BooleanField(default=True, verbose_name='37')),
                ('size38', models.BooleanField(default=True, verbose_name='38')),
                ('size39', models.BooleanField(default=True, verbose_name='39')),
                ('size40', models.BooleanField(default=True, verbose_name='40')),
                ('size41', models.BooleanField(default=True, verbose_name='41')),
                ('size42', models.BooleanField(default=True, verbose_name='42')),
                ('size43', models.BooleanField(default=True, verbose_name='43')),
                ('size44', models.BooleanField(default=True, verbose_name='44')),
                ('size45', models.BooleanField(default=True, verbose_name='45')),
                ('size46', models.BooleanField(default=True, verbose_name='46')),
                ('size47', models.BooleanField(default=True, verbose_name='47')),
                ('sizeS', models.BooleanField(default=False, verbose_name='S')),
                ('sizeM', models.BooleanField(default=False, verbose_name='M')),
                ('sizeL', models.BooleanField(default=False, verbose_name='L')),
                ('sizeXL', models.BooleanField(default=False, verbose_name='XL')),
                ('sizeXXL', models.BooleanField(default=False, verbose_name='XXL')),
                ('size3XL', models.BooleanField(default=False, verbose_name='3XL')),
                ('size4XL', models.BooleanField(default=False, verbose_name='4XL')),
                ('size5XL', models.BooleanField(default=False, verbose_name='5XL')),
            ],
        ),
    ]
