# Generated by Django 3.0.8 on 2020-08-16 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0003_auto_20200811_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='code',
            field=models.CharField(default=0, max_length=2, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(default='X', max_length=30, unique=True, verbose_name='size'),
        ),
    ]
