# Generated by Django 3.0.8 on 2020-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0004_auto_20200816_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'verbose_name': 'גודל מוצר', 'verbose_name_plural': 'גדלי מוצרים'},
        ),
        migrations.AlterField(
            model_name='productsize',
            name='code',
            field=models.CharField(default=0, max_length=2, verbose_name='קוד'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(default='X', max_length=30, unique=True, verbose_name='גודל'),
        ),
    ]
