# Generated by Django 3.0.8 on 2020-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productSize', '0005_auto_20200906_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ('code',), 'verbose_name': 'Product size', 'verbose_name_plural': 'Product sizes'},
        ),
        migrations.AlterField(
            model_name='productsize',
            name='code',
            field=models.CharField(default=0, max_length=2, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(default='X', max_length=30, unique=True, verbose_name='size'),
        ),
    ]
