# Generated by Django 3.0.8 on 2020-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200913_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'הזמנה', 'verbose_name_plural': 'הזמנות'},
        ),
        migrations.AlterField(
            model_name='order',
            name='addres',
            field=models.CharField(max_length=100, verbose_name='כתובת'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cellphone',
            field=models.CharField(max_length=20, verbose_name='נייד'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=50, verbose_name='שם לקוח'),
        ),
        migrations.AlterField(
            model_name='order',
            name='contact_man',
            field=models.CharField(max_length=50, verbose_name='איש קשר'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='אימייל'),
        ),
        migrations.AlterField(
            model_name='order',
            name='private_compeny',
            field=models.CharField(max_length=50, verbose_name='חברה פרטית'),
        ),
        migrations.AlterField(
            model_name='order',
            name='submit_date',
            field=models.DateField(auto_now=True, verbose_name='תאריך הגשה'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telephone',
            field=models.CharField(max_length=20, verbose_name='טלפון'),
        ),
    ]
