# Generated by Django 3.0.8 on 2020-08-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productColor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
    ]
