# Generated by Django 3.0.8 on 2020-08-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productColor', '0002_remove_productcolor_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='code',
            field=models.CharField(default='CC', max_length=2, verbose_name='code'),
            preserve_default=False,
        ),
    ]
