# Generated by Django 3.0.8 on 2020-08-11 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productColor', '0003_productcolor_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ('code',)},
        ),
    ]
