# Generated by Django 3.0.8 on 2020-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productColor', '0004_auto_20200811_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='code',
            field=models.CharField(max_length=2, verbose_name='קוד'),
        ),
    ]
