# Generated by Django 3.0.8 on 2020-09-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productColor', '0005_auto_20200906_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ('code',), 'verbose_name': 'צבע מוצר', 'verbose_name_plural': 'צבעי מוצרים'},
        ),
    ]
