# Generated by Django 3.0.8 on 2020-09-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productColor', '0006_auto_20200908_0426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ('code',), 'verbose_name': 'צבע מוצר', 'verbose_name_plural': 'צבעי מוצר'},
        ),
    ]
