# Generated by Django 3.0.8 on 2020-09-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productColor', '0007_auto_20200908_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ('code',), 'verbose_name': 'product color', 'verbose_name_plural': 'product colors'},
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='code',
            field=models.CharField(max_length=2, verbose_name='code'),
        ),
    ]
