# Generated by Django 3.0.8 on 2020-09-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0009_auto_20200915_1933'),
        ('productColor', '0009_auto_20200915_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcolor',
            options={'default_related_name': 'productColors', 'ordering': ('code',), 'verbose_name': 'צבע מוצר', 'verbose_name_plural': 'צבעי מוצר'},
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='productColors', serialize=False, to='color.Color'),
        ),
    ]
