# Generated by Django 3.0.8 on 2020-08-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='const_inst_client',
            field=models.IntegerField(default=0, null=True, verbose_name='cost for institucional client'),
        ),
        migrations.AddField(
            model_name='product',
            name='const_sing_client',
            field=models.IntegerField(default=0, null=True, verbose_name='cost for single client'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_prices',
            field=models.IntegerField(default=0, null=True, verbose_name='cost prices'),
        ),
        migrations.AddField(
            model_name='product',
            name='cost_prices_tax',
            field=models.IntegerField(default=0, null=True, verbose_name='cost prices + tax'),
        ),
        migrations.AddField(
            model_name='product',
            name='packing',
            field=models.CharField(choices=[('S', 'single'), ('M', '5'), ('T', '10'), ('F', '50')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
