# Generated by Django 3.0.8 on 2020-10-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='const_sing_client',
        ),
    ]
