# Generated by Django 3.0.8 on 2020-08-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200802_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing',
            field=models.CharField(choices=[('S', 'single'), ('M', '5'), ('T', '10'), ('F', '50')], default='S', max_length=1),
        ),
    ]
