# Generated by Django 3.0.8 on 2020-10-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_const_sing_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='const_sing_client',
            field=models.IntegerField(default=0, verbose_name='מחיר לקוח בודד כולל מע"מ'),
        ),
    ]
