# Generated by Django 3.0.8 on 2020-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200802_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
    ]
