# Generated by Django 3.0.8 on 2020-08-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packingType', '0001_initial'),
        ('product', '0006_auto_20200804_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='packingType.PackingType'),
        ),
    ]
