# Generated by Django 3.0.8 on 2020-08-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200804_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='const_inst_client',
        ),
        migrations.RemoveField(
            model_name='product',
            name='const_sing_client',
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_prices_tax',
        ),
        migrations.AddField(
            model_name='product',
            name='const_inst_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='cost for institucional client max'),
        ),
        migrations.AddField(
            model_name='product',
            name='const_inst_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='cost for institucional client min'),
        ),
        migrations.AddField(
            model_name='product',
            name='const_sing_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='cost for single client max'),
        ),
        migrations.AddField(
            model_name='product',
            name='const_sing_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='cost for single client min'),
        ),
    ]
