# Generated by Django 3.0.8 on 2020-08-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200804_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suport_embroidery',
            field=models.BooleanField(default=True, verbose_name='suport embroidery'),
        ),
        migrations.AddField(
            model_name='product',
            name='suport_printing',
            field=models.BooleanField(default=True, verbose_name='suport printing'),
        ),
    ]
