# Generated by Django 3.0.8 on 2020-08-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200804_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='comments'),
        ),
    ]
