# Generated by Django 3.0.8 on 2020-08-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catalogNumber',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='packing',
        ),
        migrations.RemoveField(
            model_name='product',
            name='provider',
        ),
        migrations.AddField(
            model_name='product',
            name='name_code',
            field=models.CharField(default='Aa', max_length=2, verbose_name='sub-category'),
            preserve_default=False,
        ),
    ]
