# Generated by Django 3.0.8 on 2020-08-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200809_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_prices',
        ),
    ]
