# Generated by Django 3.0.8 on 2020-08-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_product_cost_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name_code',
        ),
        migrations.AlterField(
            model_name='product',
            name='const_inst_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='to: '),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_inst_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='cost for institucional from'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_sing_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='to: '),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_sing_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='cost for single client from'),
        ),
    ]
