# Generated by Django 3.0.8 on 2020-08-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20200810_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='const_inst_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_sing_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='to'),
        ),
    ]
