# Generated by Django 3.0.8 on 2020-08-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('product', '0014_auto_20200810_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.ManyToManyField(to='stock.Stock'),
        ),
    ]
