# Generated by Django 3.0.8 on 2020-08-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stocks',
        ),
    ]
