# Generated by Django 3.0.8 on 2020-08-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_product_stocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category',)},
        ),
    ]
