# Generated by Django 3.0.8 on 2020-09-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20200815_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category',), 'verbose_name': 'מוצר', 'verbose_name_plural': 'מוצרים'},
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_inst_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='עד'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_inst_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='מחיר לקוח עסקי'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_sing_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='עד'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_sing_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='מחיר לקוח יחיד'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='תוכן'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='שם'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suport_embroidery',
            field=models.BooleanField(default=True, verbose_name='תומך רקמה'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suport_printing',
            field=models.BooleanField(default=True, verbose_name='תומך בהדפסה'),
        ),
    ]
