# Generated by Django 3.0.8 on 2020-09-08 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20200908_0426'),
        ('product', '0018_auto_20200906_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer_catalog',
            field=models.CharField(default='----', max_length=50, verbose_name='customer catalog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.Category', verbose_name='קטגוריה'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_inst_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='מחיר לקוח עסקי מ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suport_embroidery',
            field=models.BooleanField(default=True, verbose_name='תומך ברקמה'),
        ),
    ]
