# Generated by Django 3.0.8 on 2020-09-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20200908_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_catalog',
        ),
    ]
