# Generated by Django 3.0.8 on 2020-09-08 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20200908_1726'),
        ('product', '0020_remove_product_customer_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.Category', verbose_name='קטגורייה'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_inst_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='מחיר לקוח מוסדי מ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_sing_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='מחיר לקוח בודד מ'),
        ),
    ]
