# Generated by Django 3.0.8 on 2020-09-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20200913_1831'),
        ('product', '0021_auto_20200908_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='buy_cost',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='buy cost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='comments'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_inst_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_inst_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='cost for institucional without tax from'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_sing_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_sing_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='cost for single client with tax from'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suport_embroidery',
            field=models.BooleanField(default=True, verbose_name='suport embroidery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suport_printing',
            field=models.BooleanField(default=True, verbose_name='suport printing'),
        ),
    ]
