# Generated by Django 3.0.8 on 2020-09-15 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0013_auto_20200915_1933'),
        ('product', '0022_auto_20200913_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category',), 'verbose_name': 'מוצר', 'verbose_name_plural': 'מוצרים'},
        ),
        migrations.AlterField(
            model_name='product',
            name='buy_cost',
            field=models.PositiveSmallIntegerField(verbose_name='מחיר עלות'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.Category', verbose_name='קטגוריה'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='הערות'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_inst_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='עד'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_inst_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='מחיר לקוח מוסדי ללא מע"מ מ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_sing_client_max',
            field=models.IntegerField(default=0, null=True, verbose_name='עד'),
        ),
        migrations.AlterField(
            model_name='product',
            name='const_sing_client_min',
            field=models.IntegerField(default=0, null=True, verbose_name='מחיר לקוח בודד כולל מע"מ מ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='תוכן'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suport_embroidery',
            field=models.BooleanField(default=True, verbose_name='תומך ברקמה'),
        ),
        migrations.AlterField(
            model_name='product',
            name='suport_printing',
            field=models.BooleanField(default=True, verbose_name='תומך בהדפסה'),
        ),
    ]
