# Generated by Django 3.0.8 on 2020-09-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20200915_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='const_sing_client_max',
        ),
        migrations.RemoveField(
            model_name='product',
            name='const_sing_client_min',
        ),
        migrations.AddField(
            model_name='product',
            name='const_sing_client',
            field=models.IntegerField(default=0, null=True, verbose_name='cost for single client with tax'),
        ),
    ]
