# Generated by Django 3.0.8 on 2020-09-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packingType', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packingtype',
            options={'verbose_name': 'שיטת אריזה', 'verbose_name_plural': 'שיטות אריזה'},
        ),
    ]
