# Generated by Django 3.0.8 on 2020-09-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packingType', '0002_auto_20200906_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packingtype',
            options={'verbose_name': 'Packing type', 'verbose_name_plural': 'Packing types'},
        ),
    ]
