# Generated by Django 3.0.8 on 2020-09-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packingType', '0003_auto_20200913_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packingtype',
            options={'verbose_name': 'שיטת אריזה', 'verbose_name_plural': 'שיטות אריזה'},
        ),
    ]
