# Generated by Django 3.0.8 on 2020-09-08 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productImages', '0002_auto_20200906_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'תמונת מוצר', 'verbose_name_plural': 'תמונות מוצר'},
        ),
    ]
