# Generated by Django 3.0.8 on 2020-09-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20200924_2216'),
        ('productImages', '0006_auto_20200915_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'default_related_name': 'images', 'verbose_name': 'תמונת מוצר', 'verbose_name_plural': 'תמונות מוצרים'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.Product', verbose_name='מוצר'),
        ),
    ]
